// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package model

import (
	"database/sql"
)

type Episode struct {
	ShowTitle     sql.NullString
	Title         sql.NullString
	Season        sql.NullInt64
	Episode       sql.NullInt64
	TvdbID        int64
	ShowTvdbID    sql.NullInt64
	PlexRatingKey sql.NullString
	SonarrID      sql.NullInt64
	SonarrFileID  sql.NullInt64
	Downloading   sql.NullInt64
	Watched       sql.NullInt64
	HasFile       sql.NullInt64
	DownloadedAt  sql.NullInt64
	LastViewedAt  sql.NullInt64
	AirDate       sql.NullInt64
	Duration      sql.NullInt64
}

type Show struct {
	TvdbID        int64
	Title         sql.NullString
	Rating        sql.NullFloat64
	PlexRatingKey sql.NullString
	Continuing    sql.NullInt64
	SonarrID      sql.NullInt64
	LibraryID     sql.NullInt64
}
