// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: shows.sql

package model

import (
	"context"
	"database/sql"
)

const getShow = `-- name: GetShow :one
SELECT tvdb_id, title, rating, plex_rating_key, continuing, sonarr_id, library_id FROM shows
WHERE tvdb_id = ? LIMIT 1
`

func (q *Queries) GetShow(ctx context.Context, tvdbID int64) (Show, error) {
	row := q.db.QueryRowContext(ctx, getShow, tvdbID)
	var i Show
	err := row.Scan(
		&i.TvdbID,
		&i.Title,
		&i.Rating,
		&i.PlexRatingKey,
		&i.Continuing,
		&i.SonarrID,
		&i.LibraryID,
	)
	return i, err
}

const listShows = `-- name: ListShows :many
SELECT tvdb_id, title, rating, plex_rating_key, continuing, sonarr_id, library_id FROM shows
`

func (q *Queries) ListShows(ctx context.Context) ([]Show, error) {
	rows, err := q.db.QueryContext(ctx, listShows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Show
	for rows.Next() {
		var i Show
		if err := rows.Scan(
			&i.TvdbID,
			&i.Title,
			&i.Rating,
			&i.PlexRatingKey,
			&i.Continuing,
			&i.SonarrID,
			&i.LibraryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertShow = `-- name: UpsertShow :exec
INSERT INTO shows (tvdb_id, title, rating, plex_rating_key, continuing, sonarr_id, library_id)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
ON CONFLICT (tvdb_id)
    DO UPDATE SET title = @title,
                  rating = @rating,
                  plex_rating_key = @plexRatingKey,
                  continuing = @continuing,
                  sonarr_id = @sonarrId,
                  library_id = @libraryId
`

type UpsertShowParams struct {
	TvdbID        int64
	Title         sql.NullString
	Rating        sql.NullFloat64
	PlexRatingKey sql.NullString
	Continuing    sql.NullInt64
	SonarrId      sql.NullInt64
	LibraryId     sql.NullInt64
}

func (q *Queries) UpsertShow(ctx context.Context, arg UpsertShowParams) error {
	_, err := q.db.ExecContext(ctx, upsertShow,
		arg.TvdbID,
		arg.Title,
		arg.Rating,
		arg.PlexRatingKey,
		arg.Continuing,
		arg.SonarrId,
		arg.LibraryId,
	)
	return err
}
